#pragma once

#include <lvgl.h>

namespace ui {

// The interface fonts. Each is Montserrat with the Traditional Chinese subset
// attached as an LVGL fallback, so a string mixing scripts - "Wi-Fi 設定" - draws
// from both without the caller choosing.
//
// Fallback rather than one merged face on purpose: every reserved row height in
// ui_data.hpp is derived from Montserrat's line height as a literal, and
// regenerating Montserrat through the subsetter would move those metrics under
// a layout that has been tuned against them. The generated CJK faces are
// shorter than their Montserrat counterparts at every size (14 vs 16, 19 vs 22,
// 27 vs 30), so Chinese cannot overflow a box sized for Latin.
//
// Call once, after lv_init and before the first render.
void fonts_init();

// Safe before fonts_init(), which is what makes these usable from static
// initialisers: until then each returns plain Montserrat and simply renders no
// Chinese, rather than dereferencing a half-built font.
const lv_font_t* font_small();   // Montserrat 14 + CJK 14
const lv_font_t* font_medium();  // Montserrat 20 + CJK 20
const lv_font_t* font_large();   // Montserrat 28 + CJK 28
// Clock hero: a 128px Montserrat subset of the ten digits and a colon, and
// NOTHING else - no letters, no percent sign, no space, no decimal point.
//
// Two callers only: the clock hero, and the volume readout on the now-playing
// page (render_now_playing.cpp). Both pass digits and nothing else, which is
// the actual rule - ui::volume_percent_text() exists in the shape it does
// precisely so that its one non-digit return, "MUTE", never reaches this face.
// Anything else renders the missing characters as empty boxes, silently: the
// OTA page showed "WORKING" as five boxes, and neither produced a warning,
// because a missing glyph is not an overflow and not an out-of-bounds object.
// Reach for font_large() when a big number needs a unit or a sign.
//
// No CJK fallback either, because no Chinese can reach it - and a Chinese
// subset at this size would cost more per glyph than every other size
// combined.
const lv_font_t* font_hero();

// The weather icons, as a font rather than as drawing code.
//
// Seven glyphs from Weather Icons (SIL OFL 1.1, erikflowers/weather-icons) in
// the private-use range U+F002..U+F041, generated by lv_font_conv at bpp 1 -
// the same pipeline and the same bit depth as every other face here, which is
// also exactly what this panel is: one bit, no grey, no anti-aliasing to go
// wrong on a diagonal.
//
// Three sizes because a glyph cannot be scaled at runtime, each chosen to be
// the largest that fits the box it draws into.
//
// The cap is the glyph's own ink box, not the font's line_height: weather_icon
// positions by ink (see ui_theme.cpp), so a line box taller than the rect
// costs nothing. An earlier pass capped these by line_height instead and gave
// up roughly a third of the available size for no reason - the forecast icon
// in particular ran at 19px inside a box that takes 30.
//
//   large  39px, widest ink 55x43, box 56x58  (weather page hero)
//   medium 30px, widest ink 42x33, box 50x34  (forecast column)
//   small  19px, widest ink 27x21, box 28x28  (sidebar tile)
//
// The widest glyph is always day-cloudy (U+F002), a sun behind a cloud, which
// is wider than it is tall - sizing against the round sun instead would
// overflow the box the first time the sky was partly cloudy.
const lv_font_t* font_weather_large();
const lv_font_t* font_weather_medium();
const lv_font_t* font_weather_small();

}  // namespace ui
